name: dotify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hello
      run: echo Hello, world!
    - name: install graphviz
      run: |
        apt-get install graphviz
    - name: dot
      run: dot -?
