name: dotify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hello
      run: echo Hello, world!
    - name: Setup Graphviz environment
      uses: kamiazya/setup-graphviz@v1
    - name: dot
      run: dot -?
